### ISSUE TITLE
<Image source={require(some_string_var)} /> throws error

### ISSUE THREAD

**Issue by dazaevvc** [wdi-atx-12/class#4]
when passing a relative path as string explicitly it works fine. when passing exact same string in as a variable, error that source requires a string literal. we've tried source={{uri: some_string_var}} and the error goes away but no image displays. we are tearing our hair out because typeof some_string_var === 'string'

**Comment by jhnsnc** [comment]
In the title you say you are doing `source={require(some_string_var)}`. Why is the `require()` function in there?

Couldn't you just do `source={some_string_var}`? Is there some context I'm missing?

**Comment by ludocracy** [comment]
the docs for <Image /> say that source must be an object of format {uri: 'path'}: https://facebook.github.io/react-native/docs/image.html

**Comment by ludocracy** [comment]
we understand why require won't work, because it happens during build and not run-time, so a var would not resolve to a string in time. but the workarounds involve using package.json and export/import of required images as a module, but that is super complicated and we can't get it to work.

**Comment by jhnsnc** [comment]
Closing this issue. If there's something you would like additional help/ideas on, let me know.

:-)
