### ISSUE TITLE
Restoring Master to previous commit

### ISSUE THREAD

**Issue by rcgutierrez** [wdi-atx-12/class#5]
We are trying to restore our master branch to a previous commit and whenever we get to there and everything working again, it says we can't push up because that commit is behind what we have on github.

**Comment by jhnsnc** [comment]
Basically, you can only push changes up to a remote if your local branch has a matching history with the target branch, *plus* some commit(s). In this case you are trying to push up your local branch, which is the same as the target branch *minus* some commit(s).

You options are either to do a new commit that puts files back in a known-working state. Or force push an incomplete history of the branch as the full branch, breaking other collaborators' connection to the branch in the process. In the second option, you would have to get everyone else to delete their branch locally and re-download it.

The better option is to copy over the files in the known-working configuration, verify it is working, and commit those changes in a new commit.
