### ISSUE TITLE
markers on google maps

### ISSUE THREAD

**Issue by so-chow** [wdi-atx-12/class#6]
I've been trying to display Markers on my map using npm package [google-maps-react](https://github.com/fullstackreact/google-maps-react). Whenever I `console.log` what I think is the a property inherited from the parent in our Map component, it displays as undefined. I've tried console logging several things but nothing seems to work.
Some things I've tried:
`console.log(this.props);`
- returns
```
__proto__
:
constructor
:
ƒ Object()
hasOwnProperty
:
ƒ hasOwnProperty()
isPrototypeOf
:
ƒ isPrototypeOf()
propertyIsEnumerable
:
ƒ propertyIsEnumerable()
toLocaleString
:
ƒ toLocaleString()
toString
:
ƒ toString()
valueOf
:
ƒ valueOf()
__defineGetter__
:
ƒ __defineGetter__()
__defineSetter__
:
ƒ __defineSetter__()
__lookupGetter__
:
ƒ __lookupGetter__()
__lookupSetter__
:
ƒ __lookupSetter__()
get __proto__
:
ƒ __proto__()
set __proto__
:
ƒ __proto__()
```
Can we get some guidance on how to properly pass down the information needed as a property? We have only run into this issue in our Map component.

**Comment by jhnsnc** [comment]
(We were able to track down the issue with some strategically placed `console.log()`s. Turns out we were looking in the wrong component.)
